### ISSUE TITLE
Undefined name 'dumpsterFireName'

### ISSUE THREAD

**Issue by cclauss** [TryCatchHCF/DumpsterFire#1]
Undefined names can raise [NameError](https://docs.python.org/2/library/exceptions.html#exceptions.NameError) at runtime.

flake8 testing of https://github.com/TryCatchHCF/DumpsterFire on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./dumpsterFireFactory.py:706:40: F821 undefined name 'dumpsterFireName'
		print "Error opening config file " + dumpsterFireName
                                       ^

1     F821 undefined name 'dumpsterFireName'
```

**Comment by TryCatchHCF** [comment]
Fixed and uploaded - Thanks!
